general {
    lock_cmd = pidof hyprlock || hyprlock
    before_sleep_cmd = loginctl lock-session
    after_sleep_cmd = hyprctl dispatch dpms on
}

{{#if LAPTOP}}
listener {
    timeout = 5
    on-timeout = brightnessctl -sd tpacpi::kbd_backlight set 1
    on-resume = brightnessctl -sd tpacpi::kbd_backlight set 2
}

listener {
    timeout = 15
    on-timeout = brightnessctl -sd tpacpi::kbd_backlight set 0
    on-resume = brightnessctl -sd tpacpi::kbd_backlight set 2
}

listener {
    timeout = 60
    on-timeout = brightnessctl -s set 0
    on-resume = brightnessctl -r
}

listener {
    timeout = 120
    on-timeout = hyprctl dispatch dpms off && hyprlock & disown
    on-resume = hyprctl dispatch dpms on
}

listener {
    timeout = 300
    on-timeout = systemctl suspend
    on-resume = hyprctl reload
}
{{else}}
listener {
    timeout = 15
    on-timeout = pidof hyprlock && hyprctl dispatch dpms off
    on-resume = hyprctl dispatch dpms on && pidof hyprlock && hyprctl reload
}
{{/if}}
