wallpaper {
    monitor = DP-2
    path = ~/Pictures/Wallpapers/Pinkerton.jpg
    fit_mode = cover
}

wallpaper {
    monitor = DP-1
    path = ~/Pictures/Wallpapers/TDSOTM.png
    fit_mode = cover
}

wallpaper {
	monitor = HDMI-A-1
	path = ~/Pictures/Wallpapers/Sonic.png
	fit_mode = cover
}
