$font = Monospace

general {
    hide_cursor = false
    immediate_render = true
    fail_timeout = 1000
}

animations {
    enabled = true
    bezier = linear, 1, 1, 0, 0
    animation = fadeIn, 1, 4, linear
    animation = fadeOut, 1, 2, linear
    animation = inputFieldColors, 1, 1, linear
    animation = inputFieldFade, 1, 2, linear
    animation = inputFieldDots, 1, 1, linear
}

background {
    monitor =
    path = screenshot
    noise = 0.04
    contrast = 1.0
	brightness = 0.5
    blur_size = 3
    blur_passes = 3
}

input-field {
    monitor = DP-1
    size = 20%, 5%
    outline_thickness = 4
    rounding = -1

    inner_color = rgba(80808040)
    outer_color = rgb(FFFFFF) rgb(2060FF) 90deg
    check_color = rgb(C0C0C0) rgb(FFFFFF) 90deg
    fail_color = rgb(FFFFFF) rgb(FF4040) 40deg
    font_color = rgba(FFFFFFFF)

    fade_on_empty = true
    fade_timeout = 350

    font_family = Adwaita Sans Light
    placeholder_text = 
    fail_text = $PAMFAIL

    # uncomment to use a letter instead of a dot to indicate the typed password
    dots_size = 0.3
    dots_spacing = 0.4

    # uncomment to use an input indicator that does not show the password length (similar to swaylock's input indicator)
    # hide_input = true

    position = 0, -160
    halign = center
    valign = center
}

label {
    monitor = DP-2
    text = cmd[update:1000] fastfetch -l none
    font_size = 12
    font_family = MapleMonoNormal

    position = 0, 0
    halign = center
    valign = center
}

# USER
label {
    monitor = DP-1
    text = #$DESC
    color = rgb(2060FF)
    font_size = 192
    font_family = Adwaita Sans Thin

    position = 0, -96
    halign = center
    valign = top
}

# TIME12
label {
    monitor = DP-1
    text = cmd[update:100] date +'%I:%M:%S'
    color = rgb(FFFFFF)
    font_size = 192
    font_family = Adwaita Sans Light

    position = -10, -32
    halign = right
    valign = bottom
}

# DATE
label {
    monitor = DP-1
    text = cmd[update:60000] date +"%A, %d %B %Y" 
    color = rgb(C0C0C0)
    font_size = 48
    font_family = Adwaita Sans ExtraLight

    position = -30, 224
    halign = right
    valign = bottom
}

image {
	monitor = DP-1
	path = ~/Pictures/Hypr/Shutdown.png
	size = 96
    border_size = 0

    position = 8, 16
    halign = left
    valign = bottom

	onclick = sh -c "shutdown 0"
}

label {
	monitor = DP-1
	text = Shutdown
	font_size = 64
	font_family = Adwaita Sans Light

	position = 128, 16
	halign = left
	valign = bottom

}

image {
    monitor = DP-1
    path = ~/Pictures/Hypr/Reboot.png
    size = 96
    border_size = 0

    position = 8, 128
    halign = left
    valign = bottom

	onclick = sh -c "reboot"
}

label {
    monitor = DP-1
    text = Reboot
    font_size = 64
    font_family = Adwaita Sans Light

    position = 128, 128
    halign = left
    valign = bottom
}
