includes = []
packages = ["default"]

[files]

[variables]
LAPTOP=false

MONITORS = [
    { name = "DP-1", width = 2560, height = 1440, refresh_rate = 165, x=1920, y=0 },
    { name = "DP-2", width = 1920, height = 1200, refresh_rate = 165, x=0, y=180 },
    { name = "HDMI-A-1", width = 1024, height = 768, refresh_rate = 85, x=4480, y=672 }
]

MONITOR_COUNT = 3

WORKSPACES = ["DP-1", "DP-1", "DP-1", "DP-1", "DP-2", "DP-2", "DP-2", "DP-2", "HDMI-A-1"]
WORKSPACES_PER_MONITOR = 4
