includes = []
packages = ["default"]

[files]

[variables]
LAPTOP=false

MONITORS = [
    { name = "DP-1", width = 2560, height = 1440, refresh_rate = 165, x=1920, y=0 },
    { name = "DP-2", width = 1920, height = 1200, refresh_rate = 165, x=0, y=180 },
    { name = "HDMI-A-1", width = 1024, height = 768, refresh_rate = 85, x=4480, y=672 }
]

MONITOR_COUNT = 3

WORKSPACES = [
{name = "DP-1", default = true, str="m~"},
{name = "DP-1", default = false, str="m~"},
{name = "DP-1", default = false, str="m~"},
{name = "DP-1", default = false, str="m~"},
{name = "DP-2", default = true, str="m~"},
{name = "DP-2", default = false, str="m~"},
{name = "DP-2", default = false, str="m~"},
{name = "DP-2", default = false, str="m~"},
{name = "HDMI-A-1", default = true, str="m~"}
]

WORKSPACE_STR = "m~"

WORKSPACES_PER_MONITOR = 4
