[helpers]

[default]
depends = []

[default.files]
Pictures = "~/Pictures"
bin = "~/bin"
config = "~/.config"
config_untemplated = { target = "~/.config", type = "symbolic" }

[default.variables]

[settings]
default_target_type = "automatic"
