includes = []
packages = ["default"]

[files]

[variables]
LAPTOP=false

MONITORS = [
    { name = "eDP-1", width = 1920, height = 1200, refresh_rate = 60, x=0, y=0 },
    { name = "eDP-1", width = 1920, height = 1200, refresh_rate = 60, x=0, y=0 },
    { name = "eDP-1", width = 1920, height = 1200, refresh_rate = 60, x=0, y=0 }
]

MONITOR_COUNT = 1

WORKSPACES = [
{name = "eDP-1", default = true},
{name = "eDP-1", default = false},
{name = "eDP-1", default = false},
{name = "eDP-1", default = false},
{name = "eDP-2", default = false},
{name = "eDP-2", default = false},
{name = "eDP-2", default = false},
{name = "eDP-2", default = false},
]
WORKSPACES_PER_MONITOR = 8
